site_name: GH Script Manager
site_description: Documentation for GH Script Manager Blender Add-on
site_author: ghostWDFR

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: black
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Main Menu: main-menu.md
  - Settings: settings.md
  - Creating Scripts: creating-scripts.md
  - Importing Scripts: importing-scripts.md
  - Running Scripts: running-scripts.md
  - Editor Settings: editor-settings.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  - md_in_html